
# Site settings
title: Paul E. Soto
name: Paul E. Soto
subtitle: PhD Candidate in Economics
email: paul.soto@upf.edu
description: >
  PhD Candidate in Economics
baseurl: ""
url: "https://zhexjtu.github.io/"
github_username:  pesoto
disqus_baseurl: "https://zhexjtu.github.io/"
disqus_shortname: https-zhexjtu-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zhe Wang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/zhexjtu
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Paul E. Soto
    url: https://linkedin.com/pesoto
    desc: Connect with me on LinkedIn
    share: true
