
# Site settings
title: Zhe Wang
name: Zhe Wang
subtitle: Master in Applied Mathematics
email: zhewangxjtu@gmail.com
description: >
  Master in Applied Mathematics
baseurl: ""
url: "https://zhexjtu.github.io/"
github_username:  zhexjtu
disqus_baseurl: "https://zhexjtu.github.io/"
disqus_shortname: https-zhexjtu-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zhe Wang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: zhexjtu
    url: https://github.com/zhexjtu
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: 王哲
    url: https://www.linkedin.com/in/哲-王-119639170/
    desc: Connect with me on LinkedIn
    share: true
